# fly.toml app configuration file generated for order-analytics on 2023-09-22T16:40:46+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "order-analytics"
primary_region = "lax"

[build]

[env]
  PORT = "8081"
  SHOPIFY_APP_URL = "https://order-analytics.fly.dev"
  SHOPIFY_API_KEY = "c488d17c7612c4eb03da486f462aeb90"
  SCOPES = "read_orders, read_customers"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
